version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
        #condition: service_healthy

  db:
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_DATABASE: buffet
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./etc/database.sql:/docker-entrypoint-initdb.d/dump.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${DB_PASS}","--silent"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
      image: adminer
      restart: always
      ports:
          - '8081:8080'
      environment:
          - PMA_ARBITRARY=1
volumes:
    db_data: